import type { Metadata } from 'next';
import './globals.scss';
import { ThemeWrapper } from '@/components/wrapper/theme.wrapper';
import { FRAUNCES } from './style/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${FRAUNCES.className}`}>
        <ThemeWrapper> {children}</ThemeWrapper>
      </body>
    </html>
  );
}
