export const ASSEMBLER_REGISTRY = {
  MAIN: Symbol.for('MODULE::CORE:ASSEMBLER'),
  CONTROLLER: {
    MAIN: Symbol.for('MODULE::CORE:ASSEMBLER:CONTROLLER:MAIN'),
  },
  SERVICE: {
    MAIN: Symbol.for('MODULE::CORE:ASSEMBLER:SERVICE:MAIN'),
  },
  USE_CASE: {
    FIND: {
      TITLE: Symbol.for('MODULE::CORE:ASSEMBLER:USE_CASE:FIND:TITLE'),
      TEXT: Symbol.for('MODULE::CORE:ASSEMBLER:USE_CASE:FIND:TEXT'),
    },
  },
};
