export const ANIMATION_FRAMER_MOTION_REGISTRY = {
  EMERGE: {
    UP: Symbol.for('MODULES::ANIMATION:FRAMER_MOTION:EMERGE:UP'),
  },
  HOVER: {
    MOUNT: Symbol.for('MODULES::ANIMATION:FRAMER_MOTION:HOVER:MOUNT'),
  },
  INFINITY: {
    SLIDE: Symbol.for('MODULES::ANIMATION:FRAMER_MOTION:INFINITY:SCROLL'),
  },
  PROGRESS: Symbol.for('MODULES::ANIMATION:FRAMER_MOTION:PROGRESS'),
  SLIDE: {
    IN: Symbol.for('MODULES::ANIMATION:FRAMER_MOTION:SLIDE:IN'),
  },
  SVG: {
    DRAW: Symbol.for('MODULES::ANIMATION:FRAMER_MOTION:SVG:DRAW'),
  },
};
