export const ANIMATION_FRAMER_MOTION_REGISTRY = {
  PROPGRESS: Symbol.for('MODULES::ANIMATION:FRAMER_MOTION:PROGRESS'),
  SLIDE: {
    IN: Symbol.for('MODULES::ANIMATION:FRAMER_MOTION:SLIDE:IN'),
  },
  SVG: {
    DRAW: Symbol.for('MODULES::ANIMATION:FRAMER_MOTION:SVG:DRAW'),
  },
};
