export const STATIC_CMS_GATEWAY_REGISTRY = {
  PERSON: Symbol.for('MODULE::GATEWAY:CMS:STATIC:PERSON'),
  OCCUPATION: Symbol.for('MODULE::GATEWAY:CMS:STATIC:OCCUPATION'),
  ASSEMBLER: Symbol.for('MODULE::GATEWAY:CMS:STATIC:ASSEMBLER'),
};
