export const SANITY_CMS_GATEWAY_REGISTRY = {
  PERSON: Symbol.for('MODULE::GATEWAY:CMS:SANITY:PERSON'),
  OCCUPATION: Symbol.for('MODULE::GATEWAY:CMS:SANITY:OCCUPATION'),
  ASSEMBLER: Symbol.for('MODULE::GATEWAY:CMS:SANITY:ASSEMBLER'),
  HIGHLIGHT: Symbol.for('MODULE::GATEWAY:CMS:SANITY:HIGHLIGHT'),
  TECH: Symbol.for('MODULE::GATEWAY:CMS:SANITY:TECH'),
  PROJECT: Symbol.for('MODULE::GATEWAY:CMS:SANITY:PROJECT'),
  PLATFORM: Symbol.for('MODULE::GATEWAY:CMS:SANITY:PLATFORM'),
  ARTICLE: Symbol.for('MODULE::GATEWAY:CMS:SANITY:ARTICLE'),
  COMPANY: Symbol.for('MODULE::GATEWAY:CMS:SANITY:COMPANY'),
  EXPERIENCE: Symbol.for('MODULE::GATEWAY:CMS:SANITY:EXPERIENCE'),
};
