export const SANITY_CMS_GATEWAY_REGISTRY = {
  PERSON: Symbol.for('MODULE::GATEWAY:CMS:SANITY:PERSON'),
  OCCUPATION: Symbol.for('MODULE::GATEWAY:CMS:SANITY:OCCUPATION'),
  ASSEMBLER: Symbol.for('MODULE::GATEWAY:CMS:SANITY:ASSEMBLER'),
};
