export const OCCUPATION_REGISTRY = {
  MAIN: Symbol.for('MODULE::CORE:OCCUPATION'),
  STATIC: Symbol.for('MODULE::CORE:OCCUPATION:STATIC'),
  CONTROLLER: {
    MAIN: Symbol.for('MODULE::CORE:OCCUPATION:CONTROLLER:MAIN'),
    STATIC: Symbol.for('MODULE::CORE:OCCUPATION:CONTROLLER:STATIC'),
  },
  SERVICE: {
    MAIN: Symbol.for('MODULE::CORE:OCCUPATION:SERVICE:MAIN'),
    STATIC: Symbol.for('MODULE::CORE:OCCUPATION:SERVICE:STATIC'),
  },
  USE_CASE: {
    STATIC: {
      FIND: {
        ALL: Symbol.for('MODULE::CORE:OCCUPATION:USE_CASE:STATIC:FIND:ALL'),
      },
    },
    FIND: {
      ALL: Symbol.for('MODULE::CORE:OCCUPATION:USE_CASE:FIND:ALL'),
    },
  },
};
