export const OCCUPATION_REGISTRY = {
  CONTROLLER: {
    MAIN: Symbol.for('MODULE::CORE:OCCUPATION:CONTROLLER:MAIN'),
  },
  SERVICE: {
    MAIN: Symbol.for('MODULE::CORE:OCCUPATION:SERVICE:MAIN'),
  },
  USE_CASE: {
    FIND: {
      ALL: Symbol.for('MODULE::CORE:OCCUPATION:USE_CASE:FIND:ALL'),
    },
  },
};
