export const FONTS_REGISTRY = {
  MONO: {
    SPACE_MONO: Symbol.for('MODULES::FONTS:MONO:SPACE_MONO'),
    INCONSOLATA: Symbol.for('MODULES::FONTS:MONO:INCONSOLATA'),
    XANH_MONO: Symbol.for('MODULES::FONTS:MONO:XANH_MONO'),
  },
  CLASSIC: {
    FRAUNCES: Symbol.for('MODULES::FONTS:CLASSIC:FRAUNCES'),
    NEUTON: Symbol.for('MODULES::FONTS:CLASSIC:NEUTON'),
    LIBRE_BASKERVILLE: Symbol.for('MODULES::FONTS:CLASSIC:LIBRE_BASKERVILLE'),
  },
};
